const listOfRestaurant = [
  {
    data: {
      id: "255655",
      name: "Cake & Cream",
      cloudinaryImageId: "ac57cc371e73f96f812613f58457aca3",
      areaName: "Jairaj Nagar",
      costForTwo: "₹200 for two",
      cuisines: ["Bakery", "Hot-dog", "Pastry", "Cake", "Thick-shake"],
      avgRating: 4.3,
      veg: true,
      parentId: "54670",
      avgRatingString: "4",
      totalRatingsString: "20+",
    },
  },
  {
    data: {
      id: "350363",
      name: "Haldiram's Sweets and Namkeen",
      cloudinaryImageId: "25c3a7d394d6c5556b134385f7d665b0",
      areaName: "Sadar Bazaar",
      costForTwo: "₹300 for two",
      cuisines: ["North Indian", "South Indian", "Chinese", "Pizzas", "Fast Food"],
      avgRating: 4.6,
      veg: true,
      parentId: "98451",
      avgRatingString: "4.6",
      totalRatingsString: "500+",
    },
  },
  {
    data: {
      id: "154891",
      name: "Rasraj Restaurant",
      cloudinaryImageId: "egbr63ulc8h1zgliivd8",
      locality: "Civil Line",
      areaName: "Civil Lines",
      costForTwo: "₹250 for two",
      cuisines: [
        "North Indian",
        "South Indian",
        "Street Food",
        "Chinese",
        "Pizzas",
        "Fast Food",
      ],
      avgRating: 3.2,
      veg: false,
      parentId: "21876",
      avgRatingString: "4.2",
      totalRatingsString: "100+",
    },
  },
  {
    data: {
      id: "255656",
      name: "MacD",
      cloudinaryImageId: "ac57cc371e73f96f812613f58457aca3",
      areaName: "Jairaj Nagar",
      costForTwo: "₹200 for two",
      cuisines: ["Pizza", "Chicken", "Diet Coke", "Cake", "Burgers"],
      avgRating: 4.8,
      veg: true,
      parentId: "54670",
      avgRatingString: "4.4",
      totalRatingsString: "20+",
    },
  },
  {
    data: {
      id: "255657",
      name: "Cake",
      cloudinaryImageId: "ac57cc371e73f96f812613f58457aca3",
      areaName: "Jairaj Nagar",
      costForTwo: "₹200 for two",
      cuisines: ["Bakery", "Hot-dog", "Pastry", "Cake", "Thick-shake"],
      avgRating: 4.2,
      veg: true,
      parentId: "54670",
      avgRatingString: "4",
      totalRatingsString: "20+",
    },
  },
  {
    data: {
      id: "255658",
      name: "Cream",
      cloudinaryImageId: "ac57cc371e73f96f812613f58457aca3",
      areaName: "Jairaj Nagar",
      costForTwo: "₹200 for two",
      cuisines: ["Bakery", "Hot-dog", "Pastry", "Cake", "Thick-shake"],
      avgRating: 4.9,
      veg: true,
      parentId: "54670",
      avgRatingString: "4",
      totalRatingsString: "20+",
    },
  },
];
export default listOfRestaurant

